name: ASPIRE
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.8.0
  - pandas=1.5.2=py38hf11a4ad_0
  - requests=2.28.2=pypi_0
  - qianfan=0.4.11=pypi_0
  - openai=1.42.0=pypi_0
  - dash=2.18.2=pypi_0
  - mygene=3.2.2=pypi_0
  - ete3=3.1.3=pypi_0
  - zhipuai=2.1.5.20230904=pypi_0
  - flask=3.0.3=pypi_0
  - pyvis=0.3.2=pypi_0
  - dash=2.18.2=pypi_0
  - spark-ai-python=0.3.5=pypi_0      

  # R
  - r-base=4.4.2
  - babelgene=22.9
  - clusterProfiler=4.14.6
  - dplyr=1.1.4
  - tidyr=1.3.1

  - pip:
    - dash==2.18.2
    - ete3==3.1.3
    - Flask==3.1.1
    - mygene==3.2.2
    - openai==1.78.1
    - pandas==1.5.2
    - PyQt5==5.15.11
    - pyvis==0.3.2
    - qianfan==0.4.12.3
    - Requests==2.32.3
    - sparkai==0.3.0
    - zhipuai==2.1.5.20250421